// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from cosmos_like_wallet.djinni

#ifndef DJINNI_GENERATED_COSMOSLIKEMSGUNDELEGATE_HPP
#define DJINNI_GENERATED_COSMOSLIKEMSGUNDELEGATE_HPP

#include <iostream>
#include <utility>

namespace ledger { namespace core { namespace api {

struct CosmosLikeMsgUndelegate final {

    template <class Archive>
    void load(Archive& archive) {
        archive();
    }

    template <class Archive>
    void save(Archive& archive) const {
        archive();
    }
};

} } }  // namespace ledger::core::api
#endif //DJINNI_GENERATED_COSMOSLIKEMSGUNDELEGATE_HPP
