// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from cosmos_like_wallet.djinni

#ifndef DJINNI_GENERATED_COSMOSLIKEMESSAGE_HPP
#define DJINNI_GENERATED_COSMOSLIKEMESSAGE_HPP

#include <memory>
#ifndef LIBCORE_EXPORT
    #if defined(_MSC_VER)
       #include <libcore_export.h>
    #else
       #define LIBCORE_EXPORT
    #endif
#endif

namespace ledger { namespace core { namespace api {

enum class CosmosLikeMsgType;
struct CosmosLikeMsgDelegate;
struct CosmosLikeMsgDeposit;
struct CosmosLikeMsgRedelegate;
struct CosmosLikeMsgSend;
struct CosmosLikeMsgSubmitProposal;
struct CosmosLikeMsgUndelegate;
struct CosmosLikeMsgVote;
struct CosmosLikeMsgWithdrawDelegationReward;

class LIBCORE_EXPORT CosmosLikeMessage {
public:
    virtual ~CosmosLikeMessage() {}

    virtual CosmosLikeMsgType getMessageType() = 0;

    static std::shared_ptr<CosmosLikeMessage> wrapMsgSend(const CosmosLikeMsgSend & msg);

    static CosmosLikeMsgSend unwrapMsgSend(const std::shared_ptr<CosmosLikeMessage> & msg);

    /**
     * Wrap the given CosmosLikeMsgDelegate into a CosmosLikeMessage
     * @param msg The message you need to wrap.
     * @return CosmosLikeMessage A wrapped message.
     */
    static std::shared_ptr<CosmosLikeMessage> wrapMsgDelegate(const CosmosLikeMsgDelegate & msg);

    /**
     * Unwrap a message to a CosmosLikeMsgDelegate
     * @param msg The message to unwrap
     * @return CosmosLikeMsgDelegate the unwrapped message
     */
    static CosmosLikeMsgDelegate unwrapMsgDelegate(const std::shared_ptr<CosmosLikeMessage> & msg);

    /**
     * Wrap the given CosmosLikeMsgUndelegate into a CosmosLikeMessage
     * @param msg The message you need to wrap.
     * @return CosmosLikeMessage A wrapped message.
     */
    static std::shared_ptr<CosmosLikeMessage> wrapMsgUndelegate(const CosmosLikeMsgUndelegate & msg);

    /**
     * Unwrap a message to a CosmosLikeMsgUndelegate
     * @param msg The message to unwrap
     * @return CosmosLikeMsgUndelegate the unwrapped message
     */
    static CosmosLikeMsgUndelegate unwrapMsgUndelegate(const std::shared_ptr<CosmosLikeMessage> & msg);

    /**
     * Wrap the given CosmosLikeMsgRedelegate into a CosmosLikeMessage
     * @param msg The message you need to wrap.
     * @return CosmosLikeMessage A wrapped message.
     */
    static std::shared_ptr<CosmosLikeMessage> wrapMsgRedelegate(const CosmosLikeMsgRedelegate & msg);

    /**
     * Unwrap a message to a CosmosLikeMsgRedelegate
     * @param msg The message to unwrap
     * @return CosmosLikeMsgRedelegate the unwrapped message
     */
    static CosmosLikeMsgRedelegate unwrapMsgRedelegate(const std::shared_ptr<CosmosLikeMessage> & msg);

    /**
     * Wrap the given CosmosLikeMsgSubmitProposal into a CosmosLikeMessage
     * @param msg The message you need to wrap.
     * @return CosmosLikeMessage A wrapped message.
     */
    static std::shared_ptr<CosmosLikeMessage> wrapMsgSubmitProposal(const CosmosLikeMsgSubmitProposal & msg);

    /**
     * Unwrap a message to a CosmosLikeMsgSubmitProposal
     * @param msg The message to unwrap
     * @return CosmosLikeMsgSubmitProposal the unwrapped message
     */
    static CosmosLikeMsgSubmitProposal unwrapMsgSubmitProposal(const std::shared_ptr<CosmosLikeMessage> & msg);

    /**
     * Wrap the given CosmosLikeMsgVote into a CosmosLikeMessage
     * @param msg The message you need to wrap.
     * @return CosmosLikeMessage A wrapped message.
     */
    static std::shared_ptr<CosmosLikeMessage> wrapMsgVote(const CosmosLikeMsgVote & msg);

    /**
     * Unwrap a message to a CosmosLikeMsgVote
     * @param msg The message to unwrap
     * @return CosmosLikeMsgVote the unwrapped message
     */
    static CosmosLikeMsgVote unwrapMsgVote(const std::shared_ptr<CosmosLikeMessage> & msg);

    /**
     * Wrap the given CosmosLikeMsgDeposit into a CosmosLikeMessage
     * @param msg The message you need to wrap.
     * @return CosmosLikeMessage A wrapped message.
     */
    static std::shared_ptr<CosmosLikeMessage> wrapMsgDeposit(const CosmosLikeMsgDeposit & msg);

    /**
     * Unwrap a message to a CosmosLikeMsgDeposit
     * @param msg The message to unwrap
     * @return CosmosLikeMsgDeposit the unwrapped message
     */
    static CosmosLikeMsgDeposit unwrapMsgDeposit(const std::shared_ptr<CosmosLikeMessage> & msg);

    /**
     * Wrap the given CosmosLikeMsgWithdrawDelegationReward into a CosmosLikeMessage
     * @param msg The message you need to wrap.
     * @return CosmosLikeMessage A wrapped message.
     */
    static std::shared_ptr<CosmosLikeMessage> wrapMsgWithdrawDelegationReward(const CosmosLikeMsgWithdrawDelegationReward & msg);

    /**
     * Unwrap a message to a CosmosLikeMsgWithdrawDelegationReward
     * @param msg The message to unwrap
     * @return CosmosLikeMsgWithdrawDelegationReward the unwrapped message
     */
    static CosmosLikeMsgWithdrawDelegationReward unwrapMsgWithdrawDelegationReward(const std::shared_ptr<CosmosLikeMessage> & msg);
};

} } }  // namespace ledger::core::api
#endif //DJINNI_GENERATED_COSMOSLIKEMESSAGE_HPP
