// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from cosmos_like_wallet.djinni

#include "CosmosConfigurationDefaults.hpp"  // my header

namespace ledger { namespace core { namespace api {

std::string const CosmosConfigurationDefaults::COSMOS_DEFAULT_API_ENDPOINT = {"https://lcd.nylira.net/"};

std::string const CosmosConfigurationDefaults::COSMOS_OBSERVER_WS_ENDPOINT = {""};

} } }  // namespace ledger::core::api
