// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from cosmos_like_wallet.djinni

#ifndef DJINNI_GENERATED_NJSCOSMOSLIKEACCOUNT_HPP
#define DJINNI_GENERATED_NJSCOSMOSLIKEACCOUNT_HPP


#include "NJSBigIntCallback.hpp"
#include "NJSCosmosLikeTransactionBuilderCpp.hpp"
#include "NJSCosmosLikeTransactionCpp.hpp"
#include "NJSStringCallback.hpp"
#include <memory>
#include <string>

#include <nan.h>
#include <node.h>
#include "../include/CosmosLikeAccount.hpp"

using namespace v8;
using namespace node;
using namespace std;
using namespace ledger::core::api;

class NJSCosmosLikeAccount final {
public:

    static void Initialize(Local<Object> target);
    NJSCosmosLikeAccount() = delete;

    static Local<Object> wrap(const std::shared_ptr<ledger::core::api::CosmosLikeAccount> &object);
    static Nan::Persistent<ObjectTemplate> CosmosLikeAccount_prototype;

private:
    static NAN_METHOD(broadcastRawTransaction);

    static NAN_METHOD(broadcastTransaction);

    static NAN_METHOD(buildTransaction);

    /** Get estimated gas limit to set so the transaction will succeed */
    static NAN_METHOD(getEstimatedGasLimit);

    static NAN_METHOD(New);

    static NAN_METHOD(isNull);
};
#endif //DJINNI_GENERATED_NJSCOSMOSLIKEACCOUNT_HPP
