// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from cosmos_like_wallet.djinni

#ifndef DJINNI_GENERATED_NJSCOSMOSLIKEOPERATION_HPP
#define DJINNI_GENERATED_NJSCOSMOSLIKEOPERATION_HPP


#include "NJSCosmosLikeTransactionCpp.hpp"
#include <memory>

#include <nan.h>
#include <node.h>
#include "../include/CosmosLikeOperation.hpp"

using namespace v8;
using namespace node;
using namespace std;
using namespace ledger::core::api;

class NJSCosmosLikeOperation final {
public:

    static void Initialize(Local<Object> target);
    NJSCosmosLikeOperation() = delete;

    static Local<Object> wrap(const std::shared_ptr<ledger::core::api::CosmosLikeOperation> &object);
    static Nan::Persistent<ObjectTemplate> CosmosLikeOperation_prototype;

private:
    /**
     *Get operation's transaction
     *@return CosmosLikeTransaction object
     */
    static NAN_METHOD(getTransaction);

    static NAN_METHOD(New);

    static NAN_METHOD(isNull);
};
#endif //DJINNI_GENERATED_NJSCOSMOSLIKEOPERATION_HPP
